# Generated by Django 5.2.6 on 2025-09-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('valentine_contest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestant',
            old_name='created_at',
            new_name='date_joined',
        ),
        migrations.AddField(
            model_name='contestant',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='contestant_groups_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestant',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestant',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contestant',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='contestant_user_permissions_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
