# Generated by Django 5.2.6 on 2025-09-23 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valentine_contest', '0002_rename_created_at_contestant_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
